### PR TITLE
Use Ubuntu 18.04 docker image

### LINKED ISSUE #3129: Switch to Ubuntu 18.04 Docker **before** April 1st, 2023
> We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/01

https://github.com/actions/runner-images/issues/6002

### PR DESCRIPTION
**Pull request by XVilka**
# squash me

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Since GitHub removed Ubuntu 18.04 image, use Docker

**Test plan (required)**

CI is green, AppImage works.

**Closing issues**

Closes https://github.com/rizinorg/cutter/issues/3129

### CODE REVIEW

**Comment by wargio** [comment]
Requires a new version for
- https://github.com/rizinorg/cutter-deps
- https://github.com/rizinorg/cutter-deps-qt

**Comment by XVilka** [comment]
```

Run # https://github.com/rizinorg/cutter/runs/7170222817?check_suite_focus=true
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by python3)
python3: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /__t/Python/3.7.16/x64/lib/libpython3.7m.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /__t/Python/3.7.16/x64/lib/libpython3.7m.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /__t/Python/3.7.16/x64/lib/libpython3.7m.so.1.0)
python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /__t/Python/3.7.16/x64/lib/libpython3.7m.so.1.0)
```

**Comment by XVilka** [comment]
Need to decrease minimum CMake version for plugins:
```
Installing librz_yara.so to /__w/cutter/cutter/build/appdir/usr/lib/rizin/plugins
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.12 or higher is required.  You are running version 3.10.2


-- Configuring incomplete, errors occurred!
CMake Error at dist/cmake_install.cmake:72 (message):
  Failed to package rz-libyara (returned 1)
Call Stack (most recent call first):
  cmake_install.cmake:47 (include)


FAILED: CMakeFiles/install.util 
cd /__w/cutter/cutter/build && /usr/bin/cmake -P cmake_install.cmake
ninja: build stopped: subcommand failed.
```

**Comment by wargio** [comment]
> Need to decrease minimum CMake version for plugins:

no need

**Comment by XVilka** [comment]
Need also FUSE installed:
```
2023-05-15 09:59:38 (204 MB/s) - 'linuxdeployqt-continuous-x86_64.AppImage' saved [16323776/16323776]

dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
```

**Comment by wargio** [comment]
tested Appimage and works.

**Review by wargio — APPROVED** [review]

**Review by XVilka — COMMENTED** [review]
LGTM

**Pull request merged**
