### PR TITLE
Fix: Core plugin list doesn't work [#2542]

### LINKED ISSUE #2542: Core plugin list doesn't work
**Environment information**
* Operating System: macOS
* Cutter version: 23f984d37a6b1f54f2f45f84f34452302f0e11b8 based on 3bda4c97776cc8206813e131bfd200ad2535f6ba
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:  N/A

**Describe the bug**

Rizin plugin window page with core plugins is empty even though `Lcj` list multiple core plugins.

**To Reproduce**

1. Open cutter
2. Preferences/Plugins/Show Rizin plugin information
3. Select core plugin page observe it's empty
4. Run `Lcj` in console widget observe that some core plugins are loaded

 
**Expected behavior**

Core plugins are listed in the corresponding page.

**Screenshots**
Screenshot 2020-12-29 at 21 55 01

**Additional context**
```
[0x10000407c]> Lc
egg 0x7fd91e46c160 /Users/karlis/pr_os/cutter/build/Foo.app/Contents/Resources/share/rizin/plugins/core_ghidra.dylib
a2f: The reworked analysis from scratch thing
java: Suite of java commands, java help for more info
ghidra: Ghidra integration 
[0x10000407c]> Lcj
[{"Name":"a2f","Description":"The reworked analysis from scratch thing"},{"Name":"java","Description":"Suite of java commands, java help for more info"},{"Name":"ghidra","Description":"Ghidra integration"}] 
```

### PR DESCRIPTION
**Pull request by Ernest1338**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Hi,

This is my first ever pull request as well as first ever contribution to an open-source project, so sorry if i screw up somewhere. Fix was to update command name in src/core/Cutter.cpp file, line: 2471. Commit which changed the command name from Lsj to Lcj: https://github.com/rizinorg/rizin/commit/6a64ae487a6a4ff20125d4bddc9fe8e05d6053b3.

Before:
before

After:
after

**Test plan (required)**

Compile Cutter and verify that the function is now working.

**Closing issues**

closes #2542

### CODE REVIEW

**Review by ITAYC0HEN — APPROVED** [review]
Welcome Ernest! Thank you very much for this contribution ♥️
I hope you had a nice experience compiling Cutter and sending this PR. As simple as it gets, it is still useful and fixes a bug in the program.

A small note, I highly encourage you to use "feature branches" rather then committing to your fork's "master" branch. Keeping the main branch clean will make it easier for you to make future contributions. 

Thank you once again and I'm looking forward for more contributions from you! 🙂

**Comment by Ernest1338** [comment]
Thank you for your kind words! I'm still learning about git/C++ and I was commiting to master all the time (I don't know how branches work yet). I must learn more about C++ but when I do I will surely come back here to make some pull requests. ;)

**Comment by karliss** [comment]
@Ernest1338 I also highly recommend to do what was asked in the issue description and locate the commit in rizin that modified the corresponding command. Assuming you are still learning that would be a valuable exerciser for practicing to read and navigate code and it's history in git.  When working on bigger projects reading code is equally important to writing it.

**Comment by karliss** [comment]
Advice for contributing to open source projects and making pull requests. Describing in PR description exact line number and file name that you modified is somewhat useless information as such information is more clearly seen by looking at the diff in PR. When describing your changes try do it by summarizing and describing what was done at higher abstraction level than the mechanical part of text manipulation.

Some interesting observation that could have been done by looking at the commit where command was renamed. Supposedly it was broken for more than 2 years. Another useful observation is that there are a lot more plugin kinds than currently displayed so the plugin window could be expanded. But that's a work for separate PR for which an issue could be created.

**Pull request merged**
