### PR TITLE
Adjust r2 paths (Fix r2dec misssing from release package)

### LINKED ISSUE #2329: Cutter v1.11 release on Windows doesn't ship with r2dec
**Environment information**
* Operating System: Windows
* Cutter version: 1.11
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format: Any

**Describe the bug**

Cutter v1.11 on windows doesn't ship with r2dec 

**To Reproduce**

Download the v1.11 release for windows. 
Run Cutter.exe
Open a binary file
Go to the decompiler widget and observe that r2dec isn't available 

**Expected behavior**

r2dec should be shipped by default

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Use the default paths expected by r2dec build scripts. Use meson directly instead of meson.py which planned to be removed.

**Test plan (required)**

* Tests are green
* Inspect Appveyor log and make sure r2dec and r2ghidra were compiled successfully (they are post build steps so doesn't cause build failure)
* Download the build from Appveyor and make sure r2dec and r2ghidra work.

**Closing issues**
closes #2329

### CODE REVIEW

**Comment by karliss** [comment]
Tested the archive uploaded to appveyor on Windows. Reviewer should also test it.

**Comment by ITAYC0HEN** [comment]
Tested on a clean Windows 10. Cutter opened correctly and r2ghidra and r2dec are recognized in the Decompiler widget. 

:heavy_check_mark: r2ghidra is working properly.
:x: r2dec crashed


image


The log from the `pddi` command: [pddi.log](https://github.com/radareorg/cutter/files/4999401/pddi.log)


CC @wargio

**Comment by karliss** [comment]
I already reported the r2dec crash and it was supposedly fixed. Once all the CI fixes are done I will rebase this branch it will make a new build which should contain r2dec fix.

**Comment by karliss** [comment]
Just tried the latest build. R2dec crashing problem seems to be fixed.

**Review by ITAYC0HEN — APPROVED** [review]
Nice! :)

**Pull request merged**
