### PR TITLE
docker: fix and simplify build

### PR DESCRIPTION
**Pull request by ps1337**
it is what it is!

- simplify docker image build
- removed build scripts in docker folder that aren't required
- removed the option to build the cutter docker image using local files since I think no one actually uses it and I don't like the idea of maintaining two Dockerfiles that are 90% the same.
- automatically determine available cpu cores and use all cores when building cutte

### CODE REVIEW

**Comment by XVilka** [comment]
Could you please add a `cabextract` for handling the remotely fetched PDB files? I recently had to add it in Rizin's CI: https://github.com/rizinorg/rizin/pull/244/commits/2d435a1858b02c138923af3dc66adf9ebc5692fa for tests to pass.

**Comment by Surendrajat** [comment]
Can the image size be reduced? maybe keep builder/runner config? The current size (1.13GB) seems a lot.

scr

**Comment by ps1337** [comment]
OK good points, I'll update the PR in a bit 

-----Original Message-----

**Comment by ps1337** [comment]
done, image size is now down to 800mb

**Comment by XVilka** [comment]
We could try also [docker-slim](https://github.com/docker-slim/docker-slim):
> Golang application images:
>
> -   from golang:latest - 700MB => 1.56MB (minified by 448.76X)
> -   from ubuntu:14.04 - 531MB => 1.87MB (minified by 284.10X)
> -   from golang:alpine - 258MB => 1.56MB (minified by 165.61X)
> -   from centos:7 - 615MB => 1.87MB (minified by 329.14X)

**Comment by Surendrajat** [comment]
@XVilka this is cool. Got it down to 107MB. Didn't try running yet though :P

d

**Comment by Surendrajat** [comment]
@ps1337 Please also update the `.dockerignore` file while you're at it.

**Comment by ps1337** [comment]
changed the dockerignore file. what commands did you use to minify the image?

**Comment by Surendrajat** [comment]
I used this:
`dist_linux/docker-slim build --target rizin/cutter:latest --tag rizin/cutter:slim --http-probe=false --exec "ls"`
but now that I think about it, it will probably strip away the whole Cutter part. I didn't test the resulted image as I was building on a server without X forwarding.
Running `dist_linux/docker-slim build --target rizin/cutter:latest --tag rizin/cutter:slim --http-probe=false --exec "/opt/cutter/build/Cutter --help-all"` throws an error saying:
```
docker-slim[build][exec]: cmd: /opt/cutter/build/Cutter --help-all
docker-slim[build][exec]: output: qt.qpa.xcb: could not connect to display 
docker-slim[build][exec]: output: qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
docker-slim[build][exec]: output: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application ma
y fix this problem.
docker-slim[build][exec]: output: Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
docker-slim[build][exec]: exitcode: 134
```
which is reasonable without the X part. Hope it helps.

**Comment by karliss** [comment]
Now that docker doesn't use it anymore, build.sh can be removed.

**Comment by ps1337** [comment]
then I guess `build.bat` can be removed as well?

regarding docker-slim: minifying works but it obviously requires an X server to running and accessible, so this may not be fully functional in CI/CD I think. Also, we would have to make sure that docker-slim doesn't strip out any required packages. I've tested it with these commands and generated an image with ~110 mb:

```
$ mktemp /tmp/cutter_tmp.XXX.xauth
$ xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f  /tmp/cutter_tmp.yq7.xauth nmerge -
$ chmod 644  /tmp/cutter_tmp.yq7.xauth
$ docker-slim build --target rizin/cutter:latest --tag rizin/cutter:slim --http-probe=false --env DISPLAY=$DISPLAY --env XAUTHORITY=/tmp/cutter_tmp.yq7.xauth --mount /tmp/.X11-unix:/tmp/.X11-unix  --exec "/opt/cutter/build/Cutter -A 1 /bin/ls"
```

this requires user interaction to close cutter afterwards, although this can be automated I think. however there's another issue: since all unused binaries/libs are removed, we can't guarantee that everything is still present unless we have good "tests" for that. for example, my command listed above generates a working image but removes the `cabextract` image since it's not used in the analysis step. this may be hard to maintain and produce fragile images imo.

**Comment by Surendrajat** [comment]
@ps1337 wouldn't `--include-path` and `--include-path-file` be able to preserve all cutter/rizin dirs and libs? If it's possible then opening cutter GUI shouldn't be necessary. But I guess that will still make things a bit fragile.

**Comment by ps1337** [comment]
yes that can work, I might try that option and check if it works of if it's back to the original size then

**Comment by XVilka** [comment]
I think it is good already as is, and can be improved in subsequent pull requests. Would be a good to have this for the 2.0.0 release.

**Comment by ps1337** [comment]
Yep I agree 

-----Original Message-----

**Review by karliss — APPROVED** [review]

**Review by ITAYC0HEN — APPROVED** [review]

**Comment by ITAYC0HEN** [comment]
Thank you! <3

**Comment by Surendrajat** [comment]
@ps1337 I think we forgot https://github.com/rizinorg/cutter/blob/master/docker/.travis.yml :P

**Pull request merged**
