### PR TITLE
Bump rizin dev

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
LGTM but please wait for https://github.com/rizinorg/rizin/pull/3714 to be merged first, then update Rizin again.

**Comment by XVilka** [comment]
@wargio update and rebase please

**Comment by wargio** [comment]
i will push this later.

**Comment by XVilka** [comment]
Lets wait also for https://github.com/rizinorg/rizin/pull/3717 to get rid of these pesky warnings when building Cutter

**Review by XVilka — APPROVED** [review]

**Pull request merged**
