### PR TITLE
docker:  remove unused Travis CI config

### PR DESCRIPTION
**Pull request by ps1337**
we need that for the automated build :)

### CODE REVIEW

**Review by yossizap — APPROVED** [review]

**Comment by Surendrajat** [comment]
How about keeping it also within GH Actions same as rizin with automated push on updates?
https://github.com/rizinorg/rizin/blob/master/.github/workflows/ci.yml#L872:L907

**Comment by ps1337** [comment]
Sounds good, do you know how to set that up? I've only used Travis previously. 

-----Original Message-----

**Comment by Surendrajat** [comment]
Yeah so this is rizin's CI part for doing the same thing, you can copy this maybe: https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L872:L907

**Comment by XVilka** [comment]
I think this file can be removed after the migration. since Travis CI doesn't load it anyway.

**Pull request merged**
