### PR TITLE
Use meson==0.61.5 to fix libzip strcasecmp errors

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by ret2libc** [comment]
Wrong commit description though.

**Comment by thestr4ng3r** [comment]
Just wrong title after force push

**Comment by ret2libc** [comment]
I'm actually going to apply the "proper fix" for this error and probably submit the patch upstream.

**Comment by thestr4ng3r** [comment]
Sounds good. For cutter I will still downgrade for now though to not block further work here, in particular https://github.com/rizinorg/cutter/pull/2990

**Pull request merged**
