### PR TITLE
More QT6 compatibility changes

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

For now should build in minimal config  `-DCUTTER_QT6=ON -DCUTTER_ENABLE_PYTHON=OFF -DCUTTER_ENABLE_PYTHON_BINDINGS=OFF -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING=OFF`

It's necessary to manually disable CUTTER_ENABLE_KSYNTAXHIGHLIGHTING because otherwise it might find the QT5 version of it and then complain that it's incompatible with rest of QT libs which are QT6.

**Test plan (required)**

* Ubuntu 16.04 job with oldest supported Qt5 version still builds :heavy_check_mark: 
* test one of the filters QT5-:heavy_check_mark: QT6-:heavy_check_mark: 
* test that filter reset using invalidateRowsFilter works as intended  QT5-:heavy_check_mark:  QT6-:heavy_check_mark: 
* test color picker
* when built with Qt6 Cutter opens and basic functionality works :heavy_check_mark: 
* test refactored shortcuts  QT5-:heavy_check_mark:  QT6-:heavy_check_mark:
* mouse drag in graph view QT5-:heavy_check_mark: QT6-:heavy_check_mark:
* navbar drag QT5-:heavy_check_mark: QT6-:heavy_check_mark:

**Closing issues**

Related #2464

### CODE REVIEW

**Comment by karliss** [comment]
Just noticed one more crash.

**Comment by XVilka** [comment]
I wonder if it's possible to ship Qt6-based build for Windows also?
And probably migrate from VS2017 to VS2019?
That PySide + MSVC2019 bug was fixed apparently:
- https://bugreports.qt.io/browse/PYSIDE-1433
- https://github.com/microsoft/STL/issues/1300#issuecomment-789542493

**Comment by karliss** [comment]
Yes we will eventually ship QT6 based Cutter for all platforms, but it's too early for that. Is there a specific reason you are interested in VS2019?

**Comment by XVilka** [comment]
@karliss yes, they recently made ASAN available:
- https://www.kdab.com/cpp-projects-asan-windows/
- https://devblogs.microsoft.com/cppblog/asan-for-windows-x64-and-debug-build-support/

It might be helpful to provide ASAN-enabled builds for better pre-release testing on Windows

**Comment by ITAYC0HEN** [comment]
> It's necessary to manually disable CUTTER_ENABLE_KSYNTAXHIGHLIGHTING 

Does this mean that the next Cutter won't come with KSYNTAXHIGHLIGHTING?

**Comment by XVilka** [comment]
KSyntaxHighlight gained Qt6 support only recently, probably it will take time to propagate in distributions: https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/184

**Comment by karliss** [comment]
> Does this mean that the next Cutter won't come with KSYNTAXHIGHLIGHTING?

No one is switching to QT6 yet. It isn't ready yet. This PR is in 2.0.2 because some of the changes that are in Qt6 are also included in KDE Qt 5.15 patches.

Even once the QT6 support will be finished it doesn't mean removing compatibility with with QT5.  We will switch the  official release builds once we feel comfortable with it and distro maintainers will be able to switch at their pace based on readiness of other packages.

By the way current official release builds do not include KSyntaxHighlight either only some of distro specific builds do.

**Review by thestr4ng3r — APPROVED** [review]
Ran through the test plan with unpatched Qt 5.15.2 locally, and changes look good.

**Pull request merged**
