### PR TITLE
Keep topOffset history in disassembly widget.

### LINKED ISSUE #2970: Moving back and forth in the seek history does not correctly restore the right offset/relative position
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub: ./Cutter-git-2022-06-12-84b33d50bdd666825eada79a5fe0a2039bc2b1c6-x64.Linux.AppImage
  - [ ] Distribution repository
* File format:

**Describe the bug**

When in disassembly mode and clicking on a flag in one of the "middle instructions", the seek is moved to the selected flag. However when you press ESC to go back to where you previously were, the seek is hard-moved to the instruction where the flag was used, instead of showing that instruction in the  middle of the screen like before.

**To Reproduce**

1. `./Cutter-git-2022-06-12-84b33d50bdd666825eada79a5fe0a2039bc2b1c6-x64.Linux.AppImage ./test/bins/elf/ls`
2. Go to "Disassembly" tab
3. Go to `main`
4. Double Click on `setlocale` (please note that the first instruction on the disassembly tab should be `push r15` and `call    qword [setlocale] ` should be somewhere behind)
5. Press ESC to go back to where you previously were
6. At this point you are back to the `call    qword [setlocale] ` instruction, but this instruction is now placed at the top of the Disassembly tab and not in the middle like it was before jumping to `setlocale`.

**Expected behavior**

The view goes back to exactly where it was before. This is consistent with Rizin and it is done also by IDA.

**Screenshots**

Initial position:
image

After going back with ESC:
image

**Additional context**

### PR DESCRIPTION
**Pull request by beauby**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

This commit adds support for a `topOffset` history (on top of the rizin-managed history), that keeps track of the offset of the top instruction in the disassembly widget.

**Test plan (required)**

Cf. #2970 

**Closing issues**

closes #2970

### CODE REVIEW

**Comment by ret2libc** [comment]
First, thanks a lot for these PRs!
Someone will review them ASAP :)

**Review by ret2libc — COMMENTED** [review]
The change seems to work, thanks!
Only one thing: shall we also change all callbacks registered for `&CutterCore::seekChanged` to also accept the second new argument?

cc @karliss

**Comment by beauby** [comment]
@ret2libc My (superficial) understanding of Qt is that slots can ignore extra signal parameters (cf. https://doc.qt.io/qt-6/signalsandslots.html), so this might not be strictly required.

Regardless, it would make sense to implement the same history logic in the decompiler widget.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Thanks a lot!

**Pull request merged**
