### PR TITLE
Fix the padding in SimpleTextGraphView

### PR DESCRIPTION
**Pull request by mrexodia**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Before:

After:

**Test plan (required)**

Not relevant.

### CODE REVIEW

**Comment by wargio** [comment]
Requires tests on all the platforms to be sure this does not make create new issues

**Review by wargio — CHANGES_REQUESTED** [review]
needs testing

**Comment by mrexodia** [comment]
> Requires tests on all the platforms to be sure this does not make create new issues

I don't agree. The intention of the code was clearly to take `padding / 2`.

image

If you look at `addBlock` it adds the padding to both the width and the height of the block. This means either you need to offset by half the padding or add 2 times the padding to the width and height for it to align to the center.

Feel free to test on other platforms if it makes you happy though 🙂

**Comment by wargio** [comment]
no i think it is good enough by testing this on all the platforms using the nightlies from this commit

**Review by karliss — APPROVED** [review]
Looks good for me. I was initially slightly worried that this was a wrong fix for valid problem. But after looking at how the block size is calculated, looks reasonable.

**Review by XVilka — APPROVED** [review]
Looks better now on MacOS 12.6 ARM64

**Review by wargio — APPROVED** [review]

**Pull request merged**
