### PR TITLE
Cmake appimage

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/developers-docs/first-time.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/developers-docs.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

* Use CMake for building APPIMAGE
* Build and install translation files using CMake, simplifies Appimage build, installs translation files during CMake builds for preparing distro specific package
* Refactor some of resource access code. In future other parts of code doing similar things should also be moved there. This will help with accessing resources in Appimage builds, and removes some of the platform specific code for locating translation files by using Qt utilities.
* Fix RUNAPTH for embedded python executable

**Test plan (required)**

* Get travis to UPLOAD the APPIMAGE
* test that it runs on fresh Ubuntu 16.04 install
* test that it runs a newer distro
* test sample python plugin
* all included decompilers work
* bundled r2 resource are found using `eco` to list color schemes

**Related issues**
#2098

### CODE REVIEW

**Comment by karliss** [comment]
Remaining work:
* [ ] LDD output in Travis differs from what I get locally, need to be invstigated
* [ ] test that windows cmake build works, probably will need to update windows install paths

**Comment by karliss** [comment]
The problems hinted by LDD check, where partially caused by by bad check. There is some room improvements but old APPIMAGE was equally affected by this so it doesn't need to be fixed now.

**Comment by karliss** [comment]
76->101MB increase in size, need to investigate why.

**Comment by karliss** [comment]
Size difference was caused by debug symbols which are intentionally enabled when crash reporting is enabled. I assume that in the old case they got stripped. Do we care about size increase?
Assuming we do the possible improvements are:
* reduce debug information amount from -g[2] to -g1. From the description in gcc documentation g2 is default level for debuging, but g1 should be enough for backtrace.
* build with -g2 and then split it in separate file as instructed by breakpad documentation. We can upload the debug symbols as second file for release. Strip debug symbols after they have been saved.

Cutter executable size with different settings
* no debug information ~ 4-5 MB
* -g1 ~ 14 MB
* -g[2] 70-80MB  , after compression Appimage size increases only by 25 instead of 65-75MB

**Comment by ITAYC0HEN** [comment]
it's unclear to. me the test in process. Should we tag it after merge to see if it pushes the release correctly?

**Comment by ITAYC0HEN** [comment]
alright then, so tests. passed successfully? good to be merged?

**Comment by karliss** [comment]
Tests passed. The remaining question is do we care about 25MB size increase.

**Comment by ITAYC0HEN** [comment]
I personally do not, especially when the debug symbols should've been in the appimage from the first place.

To make sure, you can poll on cutter-dev

**Review by ITAYC0HEN — APPROVED** [review]

**Pull request merged**
