### PR TITLE
Update rizin submodule for rz_core_write_assembly() 

### LINKED ISSUE #2897: Cutter fails to find themes directory
**Environment information**
* Operating System: Windows 10 and Ubuntu 20.04
* Cutter version: latest - 1b271a0 
* Obtained from:
  - [x] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

Cutter fails to load rizin themes after searching for the them in the original build directory path(`RZ_PREFIX`) instead of using the relative path due to changes in `rz_path_prefix` on rizin's side.

**To Reproduce**

Download the latest windows build artifact or build from source with bundled Rizin and rename the build folder before running Cutter.
This issue isn't reproducible with the Linux AppImage.

**Expected behavior**

The themes folder path should be portable.

**Screenshots**

Capture1234

**Additional context**

Themes fail to load even after switching to `QCoreApplication::applicationDirPath` instead of `rz_path_prefix` since `rz_core_themes_load` also uses rizin's path functions to find the themes. Also, the rizin folders are installed differently in linux and windows, they should be in the same path.

### PR DESCRIPTION
**Pull request by yossizap**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

Check that artifacts work

### CODE REVIEW

**Comment by yossizap** [comment]
There's still an issue with the windows artifact don't merge yet

**Comment by thestr4ng3r** [comment]
Is the issue with the windows artifact inside this pr a regression from dev to this pr or just still the same issue? In the second case, I would like to merge this to get the `rz_core_write_assembly()` change into dev.

**Comment by thestr4ng3r** [comment]
ping @yossizap

**Comment by yossizap** [comment]
I need to open a PR in rizin with another small fix for rz_path_prefix for the themes dir to work, should be able to finish it today. Up to you if you want to merge this first and then update rizin again for the fix later. 

Sorry for the delay, was very busy for the past 2 weeks.

**Comment by thestr4ng3r** [comment]
No problem!
If this pr here does not actively break anything, let's merge it to be up to date again and also fix the rz-ghidra build problems.

**Review by thestr4ng3r — APPROVED** [review]

**Pull request merged**
