### PR TITLE
Add rz-libyara support + cutter plugin

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

cutter

### CODE REVIEW

**Review by yossizap — COMMENTED** [review]
Since it's optional, I think that the yara widget should be added as a proper CPP plugin, same as rz-ghidra. 

https://github.com/rizinorg/rz-ghidra/tree/dev/cutter-plugin

I am not a fan of adding #ifdefs for each optional plugin in our code and it is currently unprecedented. Would like to have a discussion on this with other team members before proceeding.

If there's no available API to provide the needed functionality this would be a good chance to improve our plugin API.

**Comment by wargio** [comment]
> 

yes, i wanted to do this, but the way cutter is written does not allow me to generate a valid native library without requiring the actual cutter code.
to have a working library, cutter should be split in 2 and have cutter executable and libcutter for linking native plugins

**Comment by thestr4ng3r** [comment]
We should do this: https://cmake.org/cmake/help/latest/prop_tgt/ENABLE_EXPORTS.html
And also generate cmake config files that can be used in plugin projects. Then it should work.

**Comment by wargio** [comment]
i'm not sure it will work unless we have a static lib and statically duplicate code between libs.

**Comment by wargio** [comment]
closing this PR. i will open a new one this weekend.

**Pull request closed without merging**
