### PR TITLE
Improve FindRizin.cmake on Windows

### PR DESCRIPTION
**Pull request by GustavoLCR**
Try to find rizin executable and use the paths reported by `rizin -H`

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Uses `rizin -H` output to get libs/headers paths on Windows

**Test plan (required)**

Build Cutter on Windows with `CUTTER_USE_BUNDLED_RIZIN` set to `false`. CMake should find the system rizin installation.

**Closing issues**

None

### CODE REVIEW

**Review by ret2libc — CHANGES_REQUESTED** [review]
I'm not sure what the core Cutter devs think, but IMO searching for libraries should not depend on a binary. Rizin is just an executable that uses the librz libraries and using that to find the libraries themselves seem wrong to me. @karliss @thestr4ng3r ?

**Comment by xarkes** [comment]
I agree with Riccardo, however I am not sure what is the best way to search for libraries on Windows.

**Comment by XVilka** [comment]
@ret2libc ideally - yes. But so far only Rizin executable comes with the Rizin libraries, they are unseparable for now. I suggest we merge this, and rethink later if required.

**Comment by XVilka** [comment]
@GustavoLCR please rebase this on top of the latest master, should help to make it green.

**Comment by ret2libc** [comment]
I'd leave the decision to the usual cutter devs...

@GustavoLCR @xarkes did you look at https://stackoverflow.com/questions/12075371/cmake-find-library-custom-library-location/12087044 ?

**Comment by ret2libc** [comment]
I think this can be closed. FindRizin.cmake is not necessary anymore.

**Pull request closed without merging**
