### PR TITLE
Introduce new macOS big sur icon

### PR DESCRIPTION
**Pull request by DiegoMagdaleno**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository

**Detailed description**
As you might know Apple introduced [macOS Big sur](https://www.apple.com/macos/big-sur-preview/), this completely changes the icon standard, now they are unified, as it can be shown [Here](https://cdn.cultofmac.com/wp-content/uploads/2020/06/Big-Sur-vs-Catalina-icons-2.jpg).

I own a Mac, and i'm sure many cutter users do, so to fix the inconsistency I designed this icon.

I have the editable so I can make any changes if requested. Is okay if it isn't merged. Thanks a lot for the software! Without you I wouldn't be able to learn about the internals of lots of things.

Icon Preview:

Template - Icon - App

### CODE REVIEW

**Comment by karliss** [comment]
Yes, as you guessed yourself whether this will be merged is not an easy question, but I would be happy to have a discussion about it. With cross platform tools there are always contradicting needs of being consistent with current operating system and being consistent across the platforms.

Most of the time I am in support of better integration with system where possible: avoiding unnecessary style modifications, using higher level interfaces to allow Qt automatically do the platform specific adjustments like it can be done for shortcuts,  use of native dialogs. Icon change is a bit tougher choice. I am not a big fan making subjective changes whenever Apple decides decides especially if it's something which they will change again after few releases.

How widespread is this change among other cross platform tools instead of first party apps made by Apple and software targeting primarily macOS which needs follow the Apple rules other wise risking rejection from App Store.   Do you have any examples for cross platform open source or commercial software? If yes how big is the difference between their macOS icon and icons on other platforms?

Talking about the design and ignoring topics above. I don't like the gray on black. Feels like from a quick glance at list of many programs it would look like black blob. Also the unrolled corner with binary reminds me bit of something else. Maybe Hopper, I think i have seen something even more similar but can't remember what. Does the unrolled corner make sense for "Big Sur" style icon instead of folder/stack of document style icon.

What's your opinion of something more similar existing black and white icon just using rounded corner square instead of cirecle and maybe with light shadows?

**Comment by DiegoMagdaleno** [comment]
Sure, I can try designing something that is closer to the original icon

**Comment by ITAYC0HEN** [comment]
Good work and nice initiative Diego! I too think similarly to Karliss. The logo should look very similar on different platforms. I have nothing against giving it a tweak specifically for Apple OS, but it should be just little tweak while keeping the logo very similar to the original.

**Comment by DiegoMagdaleno** [comment]
Yes, I will redesign it to be similar to the current icon soon, I have been a little busy :)

**Comment by DiegoMagdaleno** [comment]
@ITAYC0HEN @karliss Updated the icon :), now it looks like this:

Icon-MacOS-512x512@2x

Would be amazing to receive feedback

**Comment by ITAYC0HEN** [comment]
This looks good!
@thestr4ng3r what do you think? :)

**Comment by thestr4ng3r** [comment]
Yep, looks good! Do you also have any raw vector files or something else that this icon can be re-exported from if necessary?

**Comment by karliss** [comment]
Shouldn't the circle be slightly bigger to match recommended layout?

template

Tried making some quick sketches of how it would like somewhere between your initial approach and current icon. Assuming box cutter and colors are the important part not circle.  That's without shading or precise alignment. Corners for white line look a bit weird, but that's probably due to me scaling the wrong way which resulted in not having constant width.
Screenshot from 2020-11-08 13-59-57

**Comment by ITAYC0HEN** [comment]
Really like the second row!

**Comment by ITAYC0HEN** [comment]
@DiegoMagdaleno what do you think of the suggestions by Karliss? did you like it?
@karliss can we have the vectors\svg for Diego to play and maybe update the pull request?

**Comment by DiegoMagdaleno** [comment]
@ITAYC0HEN I love the icons! they are more modern and they have that Cutter style and look.

**Comment by ITAYC0HEN** [comment]
@karliss I think that we can move forward with your suggestion. They are very nice :D

**Comment by ITAYC0HEN** [comment]
Indeed, so either Karliss will do this or provide @DiegoMagdaleno and us with access to the raw files used by @karliss

**Comment by RayPS** [comment]
This my own .icns replacement, I've added a little bit of highlight and shadows, what do you think?

**Comment by karliss** [comment]
> so either Karliss will do this or provide @DiegoMagdaleno and us with access to the raw files used by @karliss

Consider my version more of sketch. The proper version should be sized and aligned using the templates provided by Apple. I don't have the software for dealing with them. Any results I had shouldn't be difficult to reproduce using the svg icon we currently have in repository.

The version made by @RayPS also looks good.

**Comment by ITAYC0HEN** [comment]
@RayPS it indeed looks good. Would you like to send a PR with it, if it is aligned with the requirements from apple? (I know nothing about it).

**Comment by karliss** [comment]
@RayPS I think you made PR in wrong repository.

**Pull request closed without merging**
