### PR TITLE
Add quick filtering to the Classes window

### PR DESCRIPTION
**Pull request by TristanCrawford**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Previously, the only way to filter classes was by source (Binary Info or Analysis)

This PR enables additional filtering by class name, exhibiting similar behavior to the strings and functions windows.

image

Hotkey | Action
-|-
`<C-f>` | Open Filter
`<Esc>` | Clear Filter

**Test plan (required)**
- Load a binary with RTTI
- Navigate to the classes window
- Type a few class names into the filter and verify it works as expected

### CODE REVIEW

**Comment by TristanCrawford** [comment]
@karliss @ITAYC0HEN @thestr4ng3r

**Comment by ITAYC0HEN** [comment]
Thank you very much! And welcome :))
Would you.mind trying to implement it without using the UI file? Via CPP directly. We're trying to slowly get rid of our usage of UI files

**Comment by TristanCrawford** [comment]
> Thank you very much! And welcome :)) Would you.mind trying to implement it without using the UI file? Via CPP directly. We're trying to slowly get rid of our usage of UI files

@ITAYC0HEN Sure! Playing around in the Cutter source has been my first interaction with QT, so I just tried to mimic what was already going on😄

Are there any examples in the repo I can reference where layouts are being created in CPP? Or is it just as simple as declaring sub-widgets as members in the header and initializing them appropriately in the constructor?

**Comment by ITAYC0HEN** [comment]
Maybe you can use ListDockWidget
https://github.com/rizinorg/cutter/pull/1700

**Comment by ITAYC0HEN** [comment]
You did great for first timer! :)
Maybe you can use ListDockWidget, subclassing it might help.
https://github.com/rizinorg/cutter/pull/1700

You can see some info here: https://cutter.re/docs/api/widgets/classListDockWidget.html

**Comment by TristanCrawford** [comment]
@ITAYC0HEN Quick update on this.

I sub-classed ListDockWidget as you suggested and dropped the UI file.

It worked well for the most part, however I'm running into an issue trying to re-implement the combo box for selecting the section.

I can seemingly add it to the layout just fine:
```cpp
ClassesWidget::ClassesWidget(MainWindow *main)
    : ListDockWidget(main, ListDockWidget::SearchBarPolicy::HideByDefault)
{
    // -- snip --
    QHBoxLayout *classSourceLayout = new QHBoxLayout();

    QComboBox *classSourceCombo = new QComboBox();
    classSourceCombo->addItem(tr("Binary Info (Fixed)"));
    classSourceCombo->addItem(tr("Analysis (Editable)"));
    classSourceCombo->setCurrentIndex(1);
    // connect(...)
    
    classSourceLayout->addWidget(new QLabel(tr("Section:")));
    classSourceLayout->addWidget(classSourceCombo);

    ui->verticalLayout->addLayout(classSourceLayout);  // `ui` Provided by ListDockWidget
    // -- snip --
}
```

But the second I uncomment that `connect`, which is virtually unchanged from the original:
```cpp
connect<void (QComboBox::*)(int)>(classSourceCombo, &QComboBox::currentIndexChanged, this, &ClassesWidget::refreshClasses);
```
Cutter kills itself before I even get the chance to select a project/binary.

I'm not sure if there's some rookie mistake I'm making in regards to where I'm connecting that signal or what... I'll try and do some debugging later, but once that's sorted it'll be ready for review.

**Comment by ITAYC0HEN** [comment]
Nice progress! :) Thank you for taking the time to go the harder route <3

@karliss can you spot any issue in the code Tristan shared?

**Comment by karliss** [comment]
From a quick glance don't see anything obvious.  But should be easy to  significantly narrow the problem using a debugger, no point to just stare at the code.

**Comment by ITAYC0HEN** [comment]
Dont you worry @TristanCrawford, if it does not go as well we can keep the initial UI implementation. That's not bad :)
So let me know what do you think and prefer

**Comment by XVilka** [comment]
@TristanCrawford have you had any luck with this? Since we are close to the release, it would be awesome to include it in [2.2](https://github.com/rizinorg/cutter/milestone/24).

**Comment by thestr4ng3r** [comment]
Superseded by #3152. Thanks for the groundwork though!

**Pull request closed without merging**
