### PR TITLE
Change Executable to Lowercase and use re.rizin.cutter everywhere

### PR DESCRIPTION
**Pull request by thestr4ng3r**
The lowercase executable name is nicer to type and fits better into UNIX envs.

In Rizin, it was decided to use `re.rizin.<lowercase-project>` for all reverse-dns ids because this conforms to all requirements of known places where such an id is needed and thus it can be consistent for all of them.

### CODE REVIEW

**Comment by karliss** [comment]
Checked the Linux and macOS packages. Both still worked,  and Cutter.app was still with the capital letter which is correct.

**Comment by karliss** [comment]
Any thoughts about the plugin and other resource lookup path?

**Comment by thestr4ng3r** [comment]
You mean things like `~/.local/share/RizinOrg/Cutter/plugins`, `~/.config/RizinOrg/Cutter.ini` and so on? That is a good point. I think if we want to change these, we should do it right now because from the last release to the next, this will change anyway. Ignoring how Qt makes these paths, I think the nicest choices would be `~/.config/rizin/cutter.ini` or `~/.config/cutter.ini` and similar. What do you think?

**Comment by XVilka** [comment]
You might coordinate with r2pm cc @ret2libc

https://github.com/rizinorg/rz-pm/pull/5#issuecomment-761519614

**Comment by ret2libc** [comment]
I think `~/.config/cutter.ini` or `~/.config/cutter/.....` would be better. WDYT?

**Comment by thestr4ng3r** [comment]
> I think `~/.config/cutter.ini` or `~/.config/cutter/.....` would be better. WDYT?

On Linux, this is a bit more standard, yeah.

**Comment by karliss** [comment]
`~/.config/rizin/cutter.ini` we will get that if we set organizationName to "rizin" instead of "RizinOrg". According to documentation it isn't used for anything else. We should proabably also set `organizationDomain` to "rizin.re" used on mac for similar purpose.

**Comment by thestr4ng3r** [comment]
We could also try not setting the organization at all and only `organizationDomain` to `rizin.re`. I'll see what I can do.

**Comment by thestr4ng3r** [comment]
There really does not seem a way to get paths without the org name in Qt applications without dirty and potentially dangerous hacks. Even using `QSettings::setPath()` makes it append an org name:
```c++
    QCoreApplication::setOrganizationName("rizin");
    QCoreApplication::setOrganizationDomain("rizin.re");
    QCoreApplication::setApplicationName("cutter");

    QSettings::setPath(QSettings::IniFormat, QSettings::UserScope, "/home/florian/custom");
    QSettings::setPath(QSettings::NativeFormat, QSettings::UserScope, "/home/florian/custom");
    qDebug() << "QSettings:" << QSettings().fileName();
    qDebug() << "QStandardPaths for settings:" << QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
    qDebug() << "QStandardPaths:" << QStandardPaths::standardLocations(QStandardPaths::AppDataLocation);
```
gives:
```
QSettings: "/home/florian/custom/rizin/cutter.conf"
QStandardPaths for settings: "/home/florian/.config"
QStandardPaths: ("/home/florian/.local/share/rizin/cutter", "/home/florian/.local/share/flatpak/exports/share/rizin/cutter", "/var/lib/flatpak/exports/share/rizin/cutter", "/usr/local/share/rizin/cutter", "/usr/share/rizin/cutter")
```

Not setting `OrganizationName` results in `/home/florian/custom/rizin.re/cutter.conf` and in addition not setting OrganizationDomain results in `/home/florian/custom/Unknown Organization/cutter.conf`.
So I think the best setting will be the above one where we get `~/.config/rizin/cutter.ini` for settings and `~/.local/share/rizin/cutter/...` for plugins and stuff.

**Review by karliss — APPROVED** [review]
"rizin/cutter" is in my opinion perfectly reasonable and significantly reduces possibility of conflict due to "cutter" name being quite generic.

**Pull request merged**
