### PR TITLE
cmake: glob translation files

### PR DESCRIPTION
**Pull request by milahu**
allow to remove translations by

```
rm -rf src/translations/*
```

translation files should be single-sourced from https://github.com/rizinorg/cutter-translations

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

### CODE REVIEW

**Comment by XVilka** [comment]
```
CMake Error: Attempt to add a custom rule to output "C:/projects/cutter/build/src/translations/cutter_pt.qm.rule" which already has a custom rule.
```

**Comment by milahu** [comment]
... because glob returns absolute paths

please try this on windows

```cmake
# note: glob returns absolute paths
file(GLOB TS_FILES
    LIST_DIRECTORIES false
    CONFIGURE_DEPENDS
    "translations/*/cutter_*.ts"
)

message("debug: TS_FILES 1 = ${TS_FILES}")

# problems with fonts
list(FILTER TS_FILES EXCLUDE REGEX "translations/ko/cutter_ko.ts$")

# #2321 handling multiple versions of a language
list(FILTER TS_FILES EXCLUDE REGEX "translations/pt-BR/cutter_pt.ts$")

message("debug: TS_FILES 2 = ${TS_FILES}")

message(FATAL_ERROR "todo")
```

`translations/pt-BR/cutter_pt.ts` should not be in `TS_FILES 2`

**Comment by milahu** [comment]
oops

**Comment by XVilka** [comment]
@milahu please rebase.

**Comment by milahu** [comment]
abandoned

**Pull request closed without merging**
