### PR TITLE
Remove the woodpecker config.

### PR DESCRIPTION
**Pull request by karliss**
At this point there is no need for it. macOS arm64 builds are now done on GHA. From what I remember it was only introduced, because at the first apple silicon devices were released GHA didn't provide any suitable runners.

Doing all the builds on same CI platform simplifies the maintenance. 

Not sure if there is anything in woodpecker management panel which needs to be disabled, beside the config removal in cutter repo.

### CODE REVIEW

**Review by Rot127 — APPROVED** [review]
@thestr4ng3r This means we can remove them in Rizin as well? Or is there something special about it?

**Review by thestr4ng3r — APPROVED** [review]
If the build on GHA arm64 works, then no need to keep this indeed. The woodpecker was introduced only because no better solution was available in GHA at that time.

**Comment by karliss** [comment]
@thestr4ng3r What about my question on woodpecker side configuration? Does it simply monitor all repos in an organization, or is there anything which needs to be disabled in their config panel so that it doesn't complain about not being able to find any configs in repo like the appveyor did?

**Comment by thestr4ng3r** [comment]
> Does it simply monitor all repos in an organization

Repos are enabled manually in woodpecker. It does not monitor all repos in the org.

It might still register that commits are pushed and that there is no config in them. But I don't think this will break anything, it takes the config from the commit it is building, not a global URL or something.
We can remove the webhook and/or disable it on woodpecker side if we want to disable it indefinitely.

**Comment by karliss** [comment]
Thanks for clarifying. As long as it doesn't complain or add any misleading messages to the commits I am fine with it.

**Pull request merged**
