### PR TITLE
Fixed build.sh constantly updating r2 and added *BSD support

### LINKED ISSUE #991: *BSD Support
*BSD support is lacking, as it incorrectly installs radare to `/usr`, not the standard `/usr/local`.

I'd assume the `build.sh` would have to take in a PREFIX argument, with a default of `/usr`, and would also have to account for the difference between `make` and `gmake`. Cutter.pro` would also have to account for the different PREFIX. The r2 `sys/install.sh` does this by checking for both `make` and `gmake`, while also grepping its help output for `gnu`. `

The FreeBSD Ports tree (`x11/radare-cutter`) is an option, but is often outdated, and requires its own `radare2` to build, and doesn't use the build from GitHub, which is what I would prefer. It also often errors on startup, executing invalid commands and opening files with erroneous paths; a problem I don't encounter if I build from the git source.

### PR DESCRIPTION
**Pull request by nullableVoidPtr**
Only tested on FreeBSD 11.2-RELEASE

When translations/ was introduced, it added an extra line to `git submodule`, making the build script always fail the radare2 check, thereby continuously updating it, whether or not the binary is built from `HEAD`. The fix for this is to `grep` for the line that has `radare2`, before piping it into `awk`.

I also added an optional argument to `build.sh` which allows the user to pass their own `PREFIX` for installing the prerequisite `radare2`, and it is also modified to tell the difference between `bsdmake` and `gmake`, by grepping its `--help` output for `GNU`

The `qmake` files are also modified to take into account BSD's preference for `/usr/local` over `/usr`, solving the issue of missing libraries when compiling on FreeBSD.

Closes #991

### CODE REVIEW

**Comment by nullableVoidPtr** [comment]
Seems to fail on Meson for some reason...

**Comment by xarkes** [comment]
Yes I think it's unrelated, some PR are failing because of some issues on Appveyor, don't worry about that.

**Comment by xarkes** [comment]
Thanks, will check again when the Appveyor bug is fixed.

**Comment by nullableVoidPtr** [comment]
Should be fixed now, right?

**Pull request merged**
