### PR TITLE
Simplify python binding include handling

### LINKED ISSUE #3188: Qt6 Python bindings - failure to build on macOS
**Environment information**
* Operating System: macOS 13.x (ARM64)
* Cutter version: https://github.com/rizinorg/cutter/commit/44917603fa48412a0471d2bba9888367ff83bf24
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: -

**Describe the bug**

1. Install Qt 6 from Homebrew
2. Build using the following CMake command: `cmake -B build -DCUTTER_QT6=ON -DCUTTER_ENABLE_SIGDB=ON -DCUTTER_PACKAGE_RZ_GHIDRA=ON -DCUTTER_PACKAGE_RZ_LIBSWIFT=ON -DCUTTER_PACKAGE_RZ_LIBYARA=ON -DCUTTER_ENABLE_PYTHON=ON -DCUTTER_ENABLE_PYTHON_BINDINGS=ON && make -C build`

Observe the error
```
[  4%] Generating Python bindings with shiboken2
(bindings) clang_parseTranslationUnit2(0x0, cmd[41]=-nostdinc -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -isystem/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -isystem/Library/Developer/CommandLineTools/usr/include -iframework/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks -fPIC -Wno-expansion-to-defined -Wno-constant-logical-operand -x c++ -std=c++17 -I/opt/homebrew/Frameworks/Python.framework/Versions/3.11/include/python3.11:/opt/homebrew/include/PySide6:/opt/homebrew/include/PySide6/QtCore:/opt/homebrew/include/PySide6/QtGui:/opt/homebrew/include/PySide6/QtWidgets:/Volumes/Sources/Rizin/cutter/build/src/bindings/CutterBindings:/Volumes/Sources/Rizin/cutter/src/core:/Volumes/Sources/Rizin/cutter/src/widgets:/Volumes/Sources/Rizin/cutter/src/common:/Volumes/Sources/Rizin/cutter/src/plugins:/Volumes/Sources/Rizin/cutter/src/menus:/Volumes/Sources/Rizin/cutter/src/.:/opt/homebrew/lib/QtCore.framework/Headers:/opt/homebrew/lib/QtCore.framework:/opt/homebrew/lib/QtWidgets.framework/Headers:/opt/homebrew/lib/QtWidgets.framework:/opt/homebrew/lib/QtCore.framework/Headers:/opt/homebrew/lib/QtCore.framework:/opt/homebrew/lib/QtGui.framework/Headers:/opt/homebrew/lib/QtGui.framework:/opt/homebrew/lib/QtDBus.framework/Headers:/opt/homebrew/lib/QtDBus.framework:/opt/homebrew/lib/QtGui.framework/Headers:/opt/homebrew/lib/QtGui.framework:/opt/homebrew/lib/QtCore.framework/Headers:/opt/homebrew/lib/QtCore.framework:/opt/homebrew/lib/QtDBus.framework/Headers:/opt/homebrew/lib/QtDBus.framework:/Volumes/Sources/Rizin/cutter/build/Rizin-prefix/include/librz:/Volumes/Sources/Rizin/cutter/build/Rizin-prefix/include/librz/sdb:/Volumes/Sources/Rizin/cutter/src -I/opt/homebrew/lib/QtCore.framework/Headers -I/opt/homebrew/lib/QtCore.framework -I/opt/homebrew/lib/QtWidgets.framework/Headers -I/opt/homebrew/lib/QtWidgets.framework -I/opt/homebrew/lib/QtCore.framework/Headers -I/opt/homebrew/lib/QtCore.framework -I/opt/homebrew/lib/QtGui.framework/Headers -I/opt/homebrew/lib/QtGui.framework -I/opt/homebrew/lib/QtDBus.framework/Headers -I/opt/homebrew/lib/QtDBus.framework -I/opt/homebrew/lib/QtGui.framework/Headers -I/opt/homebrew/lib/QtGui.framework -I/opt/homebrew/lib/QtCore.framework/Headers -I/opt/homebrew/lib/QtCore.framework -I/opt/homebrew/lib/QtDBus.framework/Headers -I/opt/homebrew/lib/QtDBus.framework -I/Volumes/Sources/Rizin/cutter/src/core -I/Volumes/Sources/Rizin/cutter/src/widgets -I/Volumes/Sources/Rizin/cutter/src/common -I/Volumes/Sources/Rizin/cutter/src/plugins -I/Volumes/Sources/Rizin/cutter/src/menus -I/Volumes/Sources/Rizin/cutter/src -I/Volumes/Sources/Rizin/cutter/build/Rizin-prefix/include/librz -I/Volumes/Sources/Rizin/cutter/build/Rizin-prefix/include/librz/sdb /private/var/folders/x9/k5dys75d2vg49zqcw82546680000gq/T/bindings_IRijpp.hpp "-DQT_ANNOTATE_ACCESS_SPECIFIER(a)=__attribute__((annotate(#a)))" "-DQT_ANNOTATE_CLASS(type,...)=static_assert(sizeof(#__VA_ARGS__),#type);" -DQSIMD_H)
/opt/homebrew/lib/QtCore.framework/Headers/qstring.h:14:10: fatal error: 'QtCore/qchar.h' file not found
(bindings) Errors in -DQSIMD_H:
/opt/homebrew/lib/QtCore.framework/Headers/qstring.h:14:10: fatal: 'QtCore/qchar.h' file not found
   /private/var/folders/x9/k5dys75d2vg49zqcw82546680000gq/T/bindings_IRijpp.hpp:1:10: note: in file included from /private/var/folders/x9/k5dys75d2vg49zqcw82546680000gq/T/bindings_IRijpp.hpp:1:
   /Volumes/Sources/Rizin/cutter/src/bindings/bindings.h:7:10: note: in file included from /Volumes/Sources/Rizin/cutter/src/bindings/bindings.h:7:
   /Volumes/Sources/Rizin/cutter/src/core/Cutter.h:4:10: note: in file included from /Volumes/Sources/Rizin/cutter/src/core/Cutter.h:4:
   /Volumes/Sources/Rizin/cutter/src/core/CutterCommon.h:9:10: note: in file included from /Volumes/Sources/Rizin/cutter/src/core/CutterCommon.h:9:
   /opt/homebrew/lib/QtCore.framework/Headers/QString:1:10: note: in file included from /opt/homebrew/lib/QtCore.framework/Headers/QString:1:


(bindings) Clang: 1 diagnostic messages:
  /opt/homebrew/lib/QtCore.framework/Headers/qstring.h:14:10: fatal: 'QtCore/qchar.h' file not found
   /private/var/folders/x9/k5dys75d2vg49zqcw82546680000gq/T/bindings_IRijpp.hpp:1:10: note: in file included from /private/var/folders/x9/k5dys75d2vg49zqcw82546680000gq/T/bindings_IRijpp.hpp:1:
   /Volumes/Sources/Rizin/cutter/src/bindings/bindings.h:7:10: note: in file included from /Volumes/Sources/Rizin/cutter/src/bindings/bindings.h:7:
   /Volumes/Sources/Rizin/cutter/src/core/Cutter.h:4:10: note: in file included from /Volumes/Sources/Rizin/cutter/src/core/Cutter.h:4:
   /Volumes/Sources/Rizin/cutter/src/core/CutterCommon.h:9:10: note: in file included from /Volumes/Sources/Rizin/cutter/src/core/CutterCommon.h:9:
   /opt/homebrew/lib/QtCore.framework/Headers/QString:1:10: note: in file included from /opt/homebrew/lib/QtCore.framework/Headers/QString:1:


Keeping temporary file: /private/var/folders/x9/k5dys75d2vg49zqcw82546680000gq/T/bindings_IRijpp.hpp
shiboken: Error running ApiExtractor.
```

See https://github.com/rizinorg/cutter/pull/2952

### PR DESCRIPTION
**Pull request by karliss**
* remove duplicate code introduced in #2952
* specify include path using  multiple include-path lines instead  instead of single line with with directories separated by ; or :

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Looks like shiboken6 slightly changed the rules of bindings.txt and now include-path entry doesn't allow multiple include directories. Generating multiple include-path entries, one for each directory seems to work fine both for shiboken6 an shiboken2.

I am not too happy about the way I handled macOS include path, but I guess it's no worse than what was already there for qt5 (likely due to similar reasons).

**Test plan (required)**

* [x] CI builds still work
* [x]  Arch Linux qt6 with bundled rizin 
* [x]  Arch Linux qt5 with bundled rizin  *
* [x]  Arch Linux qt6 with rizin installed in random user dir
* [x] macOS homebrew qt6 bundled rizin #3188
* [x] NixOS with qt6 as reported by @chayleaf 
* build attempts on any other distro or OS are welcome

\*  had to comment out `Py_LIMITED_API` seems like shiboken2 isn't tested against latest python  . Otherwise it error on this code in shiboken2/pep384impl.h :

```
// This definition breaks the limited API a little, because it re-enables the
// buffer functions.
// But this is no problem as we check it's validity for every version.

#define PYTHON_BUFFER_VERSION_COMPATIBLE    (PY_VERSION_HEX >= 0x03030000 && \
                                             PY_VERSION_HEX <  0x030AFFFF)
#if !PYTHON_BUFFER_VERSION_COMPATIBLE
# error Please check the buffer compatibility for this python version!
#endif
```

**Closing issues**

closes #3188

### CODE REVIEW

**Comment by chayleaf** [comment]
this builds fine for me on NixOS with Pyside6. And yes, Shiboken2 requires Python 3.10

**Review by XVilka — APPROVED** [review]

**Comment by chayleaf** [comment]
As @lilyinstarlight mentioned, this fixes the Nix build on Linux, but not on Darwin.

**Comment by karliss** [comment]
@lilyinstarlight Can you retest with Nix on macOS? Tested that homebrew still works on my system.  It ended up being based on QT6_INSTALL_PREFIX anyway, but at least now it's closer to what pyside is doing.  

Definition of QT_FRAMEWORK_INCLUDE_DIR
https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/pyside6/cmake/PySideSetup.cmake?h=6.6.1#n134 
Usage:
https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/pyside6/cmake/Macros/PySideModules.cmake?h=6.6&id=v6.6.0#n146

**Comment by lilyinstarlight** [comment]
> Can you retest with Nix on macOS?

Yep, the latest commit seems to work great for building with Qt6 from Nix now. Thank you! ❤️

**Pull request merged**
