### PR TITLE
Fix #2657 - Set cutter executable as WINDOWS subsystem

### LINKED ISSUE #2657: Unexpected CMD launched with Cutter with no way of hiding or closing
**Environment information**
* Operating System: Windows 10
* Cutter version: 2.0.0
* File format: PE
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Using the Cutter.exe binary to launch the program also launches a Command Prompt immediately with the File Selection dialog. I am not sure if this was the intention, as I do not see it in the release notes or images (unless I am missing it).

**To Reproduce**
1. Launch Cutter using Cutter.exe

**Expected behavior**
Launching Cutter using the Cutter.exe binary will launch the application with the Select File dialog without a Command Prompt window or have the Command Prompt window hidden or close after file is selected.

**Screenshots**
ShareX-04-02-21_560
ShareX-04-02-21_563

**Additional context**
This is based on the previous release version 1.12.0

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Set cutter as a GUI application so it doesn't launch a console on open. 

**Test plan (required)**

* Open cutter by double-clicking
* Open cutter through console

**Closing issues**

Fixes #2657

### CODE REVIEW

**Review by yossizap — APPROVED** [review]
LGTM, tested with the github artifact.

**Comment by ITAYC0HEN** [comment]
How does it work with stdout redirection?

**Comment by yossizap** [comment]
`dbg.create_new_console` opens a new window for the debugee, we don't redirect to the console widget in Windows.

**Comment by XVilka** [comment]
Should it be merged then? cc @ITAYC0HEN @karliss @xarkes

**Comment by xarkes** [comment]
I haven't tested it myself so I have no idea. But @yossizap approved so I guess we can merge!

**Comment by ITAYC0HEN** [comment]
Thank you Gustavo! Sorry for the delay in merging

**Pull request merged**
