### PR TITLE
TypesInteractionDialog: use RzType API to edit a single type

### LINKED ISSUE #2746: Editing Types is broken
https://user-images.githubusercontent.com/1460997/132853763-5e701102-e4e2-4a13-a35c-7e6649e3bc61.mov

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Pass the type name to the TypesInteractionDialog, so it knows what type
is being changed.

**Test plan (required)**

Open /bin/ls, go to Types view, right-click on a Struct type, try to change it.

**Closing issues**

Closes #2746

### CODE REVIEW

**Comment by ret2libc** [comment]
There is a problem though.

I'm on Fedora 33, I try to edit the __imaxdiv_t. When I press ok it seems it worked, but then the __imaxdiv_t type just disappears from the list of types... I'm unsure what's happening though, the API seems to be called correctly.

**Comment by xarkes** [comment]
Funny, I have the same behavior here.

**Comment by XVilka** [comment]
Strange, since `toe __imaxdiv_t` works in Rizin

**Review by XVilka — APPROVED** [review]

**Comment by xarkes** [comment]
So I didn't follow, what fixed the issue you mentioned?
Was it https://github.com/rizinorg/rizin/pull/1695?

**Comment by ret2libc** [comment]
No it was because toutf8 was going out of scope and destroyed immediately at the same line where it was defined. By moving the toutf8.constdata inline we ensure the steering live long enough

**Review by xarkes — APPROVED** [review]

**Comment by XVilka** [comment]
@thestr4ng3r @xarkes should we merge this then?

**Pull request merged**
