### PR TITLE
create keyboard shortcuts for widgets (solve #733)

### PR DESCRIPTION
**Pull request by yahav-a**
solve  #733 

The widgets are implemented as a map between the class name and it's `QKeySequence`, in a new file at  `src/widgets/WidgetShortcuts.h`.

The choice of class name as the "Key" to the map originated from the fact the class name could be determined automatically in compile-time. However, I could only get the decorated (not demangled) name in compile time, and this name is different for different compilers.

as a demonstration, I currently added the following shortcuts:  

| Widget  | Shortcut  |
|---------|-----------|
| Strings | Shift+F12 |
| Graph   | Shift+G   |
| Imports | Shift+I   |
| Exports | Shift+E   |  

I've looked at how to make the shortcuts configurable by the users (from the settings), and basically `QKeySequence` could be mapped easily to/from strings. But we do need to decide on how (and where) to store the mapping, and what are the default values.

### CODE REVIEW

**Comment by xarkes** [comment]
Lgtm.

**Comment by kernelm0de** [comment]
Looks good, but you forgot about the widget options in main menu. Whilte toggling the widgets you need to check the options in main menu

string

**Comment by kernelm0de** [comment]
Yeah i would go with 2nd too, No need to recheck all of them as we know which needs to be changed.

**Comment by xarkes** [comment]
Looks good to me.

**Pull request merged**
