### PR TITLE
Add JSDec packaging for macos.

### LINKED ISSUE #2564: Add JSDec to macOS package build
**Is your feature request related to a problem? Please describe.**

 #2563 will soon re-enable JSDec for windows and Linux builds. During macOS cmake packaging task JSDec wasn't compatible with rizin so packaging for macOS wasn't implemented.

**Describe the solution you'd like**

* Add the required code to dist/CMakelist.txt for building and packaging JSDec on macOS similar to how it's done with JSDec on windows and Ghidra on all platforms.
* Enable CUTTER_PACKAGE_JSDEC option in CI

**Describe alternatives you've considered**
**Additional context**

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

* Download CI build
* make sure decompiler works

**Closing issues**

Closes #2564

### CODE REVIEW

**Comment by karliss** [comment]
It currently builds but causes a crash. Some debugging indicates that there are two problems:
* JSDEC_HOME isn't set up properly this shouldn't be difficult to fix
* JSDec trying to print error about JSDEC_HOME using rz_cons_strcat causes a crash

**Comment by karliss** [comment]
Some info on the the crash. Here is a stacktrace https://dpaste.org/K4Z0 . From what I observed in debugger and with debug printfs `I.context` somehow gets set to null, but I couldn't find where or how.

**Comment by thestr4ng3r** [comment]
Another issue with builds from GitHub Actions:
```
rz_lib_dl_open: error: /Applications/Cutter.app/Contents/Resources/share/rizin/plugins/libcore_pdd.dylib (dlopen(/Applications/Cutter.app/Contents/Resources/share/rizin/plugins/libcore_pdd.dylib, 9): Library not loaded: /Users/runner/work/cutter/cutter/build/Rizin-prefix/lib/librz_core.0.1.0.dylib
  Referenced from: /Applications/Cutter.app/Contents/Resources/share/rizin/plugins/libcore_pdd.dylib
  Reason: image not found)
Cannot open library: '/Applications/Cutter.app/Contents/Resources/share/rizin/plugins/libcore_pdd.dylib'
```
Looks like the jsdec lib needs some additional rpath adjustment

**Comment by karliss** [comment]
@thestr4ng3r That's not another issue, that's the same issue as one causing crash. When  I do local build macOS is capbable of loading those libraries using absoute paths which results with 2 copies of librz_cons being loaded but only one of them being initialized.  Fixing the library paths will also fix the crash.

**Comment by thestr4ng3r** [comment]
Ah yes, that would indeed explain it.

**Comment by karliss** [comment]
This is partially caused by https://github.com/rizinorg/rizin/issues/392 . `rizin -H` prints absolute paths to original build directory instead of Cutter.app, if it pointed to libs insided Cutter.app plugin should work since the libs in Cutter.app have their `LC_ID_DYLIB` updated to use rpath.

**Comment by karliss** [comment]
That should fix the linking issue, ensuring JSDEC_HOME is correctly located remains.

**Review by yossizap — APPROVED** [review]
LGTM, tested with Ubuntu 20.04

**Review by ITAYC0HEN — APPROVED** [review]

**Pull request merged**
