### PR TITLE
Disable asm.dwarf

### PR DESCRIPTION
**Pull request by xarkes**
This commit sets the asm.dwarf option to false by default and adds a
checkbox in the configuration menu to enable it.

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

By default, `asm.dwarf` is enabled. This adds a lot of verbosity to the code especially source code file lines and such which most of the time are not relevant during reverse engineering tasks. Disabling it by default makes the interface much cleaner.

image
image

**Test plan (required)**

- Open a binary with dwarf information, make sure that `e asm.dwarf` is set to false
- Enable it in the configuration panel and check that the extra  comments appear/disappear as one would expect

### CODE REVIEW

**Comment by Maijin** [comment]
I think would be nice to only enable the option if there is actual dwarf - maybe it should also notify the user?

**Comment by xarkes** [comment]
I added screenshots in case it was not clear. I especially want to disable it when dwarf information is present, as you can see there are too many useless information.

**Comment by Maijin** [comment]
I understand that - but I'm suggesting two two ideas to go a step further:

-> If dwarf not present, hide (gray out) the option from the menu
-> if dward present, add a pop-up at the opening or something that let the user know about dwarf. Like you say it's too verbose for now, so this can probably be for later.

**Comment by ITAYC0HEN** [comment]
@xarkes do you wish to implement the popup in this PR or never? (sorry, I meant "later" :D )

**Comment by XVilka** [comment]
Other tools also parse DWARF information by default if present. Why wouldn't you - it makes reverse engineering easier/

**Comment by XVilka** [comment]
I think instead of `asm.dwarf` it is better to do the following:
- Introduce `dwarf.*` config options in Rizin (we have ones for `pdb.*` anyway already)
- Add `dwarf.lines` option to show the lines info
- The rest of the information - types, function names/signatures, etc is more useful
- PROFIT

**Comment by xarkes** [comment]
Exactly, I think in the meantime we can merge or close this PR and open an issue on Rizin.

**Comment by ITAYC0HEN** [comment]
Well, meantime you can enable it back by default but keep the preferences check box in there and then let's merge

**Comment by karliss** [comment]
I support keeping it on by default. The annoyingly verbose and useless case happens when the file is compiled from assembly file (you seem to be looking at part of go runtime which is indeed written in assembly), as a result no line content because it would be more or less identical with disassembly  and line numbers  for every instruction because there is almost 1:1 match.

In case of executables or their parts compiled from C or other programming language it would be less dense and show the actual source code making it more useful. I would expect in most cases debug information to be either fully stripped or contain useful information. Is there a common case where it's only partially stripped leaving useless information?


@XVilka Does rizin really need two almost identical  sets of options for controlling type of debug information displayed depending of whether it came from pdb  or dwarf? Why not `asm.debug.lines` instead of `asm.pdb.lines` and `asm.dwarf.lines`?

**Comment by XVilka** [comment]
@karliss you are right, there is no need for this and one variable like `asm.debug.lines` should be enough.

**Comment by xarkes** [comment]
I prefer to close this PR rather than merging a temporary feature. For reference here is the issue I opened on Rizin: https://github.com/rizinorg/rizin/issues/653

**Pull request closed without merging**
