### PR TITLE
CutterCore: select the right RzReg based on debug/emulation status

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

### CODE REVIEW

**Review by thestr4ng3r — APPROVED** [review]

**Comment by ret2libc** [comment]
Do not merge as I'm still testing

**Comment by ret2libc** [comment]
Needs https://github.com/rizinorg/rizin/pull/2734 in order to work.

Emulation seems to work fine on MacOS. Debugging hangs somehow.. but i'm on mac.

**Comment by thestr4ng3r** [comment]
@ret2libc I have reverted a few changes so we can solve things a bit differently. Can you elaborate what exactly the problem was that the parts in https://github.com/rizinorg/cutter/pull/2977/commits/95610853a5d4aad9ce10ecfdd88b1edfa84348a2 fixed?

**Comment by ret2libc** [comment]
> @ret2libc I have reverted a few changes so we can solve things a bit differently. Can you elaborate what exactly the problem was that the parts in [9561085](https://github.com/rizinorg/cutter/commit/95610853a5d4aad9ce10ecfdd88b1edfa84348a2) fixed?

I guess I didn't like the fact that Cutter has to choose what to do there, as I think RzCore should hide all those details. The difference between analysis->reg and dbg->reg makes thing a bit harder, but I'm ok this way as well.

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
Looks good, though I personally think it should be done by the Rizin API itself, maybe in the future versions.

**Comment by thestr4ng3r** [comment]
> > @ret2libc I have reverted a few changes so we can solve things a bit differently. Can you elaborate what exactly the problem was that the parts in [9561085](https://github.com/rizinorg/cutter/commit/95610853a5d4aad9ce10ecfdd88b1edfa84348a2) fixed?
> 
> I guess I didn't like the fact that Cutter has to choose what to do there, as I think RzCore should hide all those details. The difference between analysis->reg and dbg->reg makes thing a bit harder, but I'm ok this way as well.

I agree on the concept. `rz_core_reg_filter_items_sync()` is also as it is a bit strange to use from the outside, as the callback-based syncing was primarily designed to be used inside RzCore command handlers, to avoid code duplication there. Ideally Cutter should not have to care about syncing anything at all and it should happen automatically, so this is indeed some place to improve the core api.

**Pull request merged**
