### PR TITLE
Merge `dev` into `stable` for 2.2 release

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Release notes**

```md
This version of Cutter is built with Rizin [0.5.0](https://github.com/rizinorg/rizin/releases/tag/v0.5.0)/[0.5.1](https://github.com/rizinorg/rizin/releases/tag/v0.5.1)

This release mostly focuses on fixing various issues with analysis and user interface. Qt6 compatibilty was also improved.

Thanks to many changes in rizin and rz-ghidra, the stack analysis was greatly improved.

Chinese, Russian, German translations were extensively updated.

Due to the rare use of Breakpad-based crash reporting, this feature was removed to ease the maintenance.
```

### CODE REVIEW

**Comment by XVilka** [comment]
Ignore Linux workers - its Ubuntu 18.04 deprecation brownout: February 21, 10.00 UTC – February 21, 22.00 UTC
https://github.com/actions/runner-images/issues/6002
I will restart once this stupid brownout period is over

**Review by wargio — APPROVED** [review]
looks good to me, just wait for the others

**Comment by wargio** [comment]
do we need to bump the version or is already 2.2 on dev?

**Comment by XVilka** [comment]
@wargio I added bumping version commit as well: https://github.com/rizinorg/cutter/pull/3135/commits/dd34c97a92fe4fde8384f5e2427499890e5de27b

**Comment by XVilka** [comment]
My bad, it requires more changes: https://github.com/rizinorg/cutter/commit/8e232bed9107f54b1dea48d50898d88c2a308525

**Review by wargio — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]
Seems ok on MacOS M1.

**Pull request closed without merging**
