### PR TITLE
Yara plugin + fix linuxdeployqt plugins

### LINKED ISSUE #2925: Add rz-libyara build to release CI
If we want rz-libyara to not break it should be checked in the CI before each release. It should have a job similar to build-rzpipe and build-extras.

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Adds flags to install yara native plugin and fixes ghidra native plugin on AppImage

- [x] Tested on Linux
- [x] Tested on OSX
- [x] Tested on Windows

Closes https://github.com/rizinorg/cutter/issues/2925

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by thestr4ng3r** [comment]
What was broken about ghidra in the AppImage that this fixes?
Also, do we even want the yara plugin in the releases at all?

**Comment by wargio** [comment]
> What was broken about ghidra in the AppImage that this fixes? Also, do we even want the yara plugin in the releases at all?

There was no ghidra plugin on cutter linux image because the native plugin was excluded from the appimage also the paths are completely different from what was set previously

**Comment by wargio** [comment]
> What was broken about ghidra in the AppImage that this fixes? Also, do we even want the yara plugin in the releases at all?

**Comment by wargio** [comment]
image
Windows

**Comment by wargio** [comment]
image
Linux

**Comment by wargio** [comment]
image
OSX

**Review by XVilka — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
Works but needs better help or documentation, or the interface.

**Comment by wargio** [comment]
image
Windows with rizin stable.
@XVilka

**Comment by deroad** [comment]
image
OSX

**Comment by wargio** [comment]
image
Linux

**Review by XVilka — APPROVED** [review]

**Pull request merged**
