### PR TITLE
Update rizin and fix it

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

### CODE REVIEW

**Comment by b1llow** [comment]
@ret2libc it seems to have some problems. But I can't reproduce it with the same compiler and Windows SDK version, what do you think?

https://github.com/rizinorg/rizin/pull/2811

```
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2332: 'struct': missing tag name
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2556: '*__timezone(void)': overloaded function differs only by return type from 'long *__timezone(void)'
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(74): note: see declaration of '__timezone'
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2371: '__timezone': redefinition; different basic types
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\time.h(74): note: see declaration of '__timezone'
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(18): error C2491: '__timezone': definition of dllimport function not allowed
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(24): error C2332: 'struct': missing tag name
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(24): error C2143: syntax error: missing ',' before '*'
c:\projects\cutter\build\include\librz\rz_util/rz_time.h(24): error C2059: syntax error: '*'

```

**Comment by ret2libc** [comment]
Could you try this patch?

```diff
diff --git a/librz/include/rz_util/rz_time.h b/librz/include/rz_util/rz_time.h
index 685b02db41..14099821c9 100644
--- a/librz/include/rz_util/rz_time.h
+++ b/librz/include/rz_util/rz_time.h
@@ -13,6 +13,7 @@
 #define ASCTIME_BUF_MINLEN 26

 #ifdef _MSC_VER
+#include <rz_windows.h>
 struct timeval;

 struct timezone {
```

**Comment by imbillow** [comment]
> Could you try this patch?
> 
> ```diff
> diff --git a/librz/include/rz_util/rz_time.h b/librz/include/rz_util/rz_time.h
> index 685b02db41..14099821c9 100644
> --- a/librz/include/rz_util/rz_time.h
> +++ b/librz/include/rz_util/rz_time.h
> @@ -13,6 +13,7 @@
>  #define ASCTIME_BUF_MINLEN 26
> 
>  #ifdef _MSC_VER
> +#include <rz_windows.h>
>  struct timeval;
> 
>  struct timezone {
> ```

`rz_windows.h` is in librc/include but not in `include_directories` of rz_util

**Comment by ret2libc** [comment]
Did you use `#include "rz_windows.h"` because you already tried `#include <rz_windows.h>`? I think the latter should be right.

**Comment by b1llow** [comment]
> Did you use `#include "rz_windows.h"` because you already tried `#include <rz_windows.h>`? I think the latter should be right.

i tried it all

**Comment by ret2libc** [comment]
> > Did you use `#include "rz_windows.h"` because you already tried `#include <rz_windows.h>`? I think the latter should be right.
> 
> i tried it all

Could you put <rz_windows.h> though? Using "rz_windows.h" does not work at all because it can't find the file.

**Comment by b1llow** [comment]
@ret2libc It found it, but it still didn't solve the original problem

**Comment by ret2libc** [comment]
@GustavoLCR do you have hints on how to solve this?

**Comment by b1llow** [comment]
https://docs.microsoft.com/en-us/cpp/c-runtime-library/daylight-dstbias-timezone-and-tzname

**Comment by ret2libc** [comment]
We use timezone name though, not _timezone

**Comment by b1llow** [comment]
> We use timezone name though, not _timezone

https://docs.microsoft.com/en-us/cpp/c-runtime-library/compatibility?view=msvc-170

Maybe some POSIX names are exported by default in older versions of UCRT,
which includes `timezone`

A `#define` I guess, maybe something else

**Comment by XVilka** [comment]
@imbillow since your PR was merged, along with the version function change - please update the Rizin and also change the function call.

**Comment by b1llow** [comment]
OK

image

**Review by XVilka — APPROVED** [review]

**Pull request merged**
