### PR TITLE
Fix build failures when compiling Cutter with Rizin's dev

### LINKED ISSUE #3239: Compilation error: cannot convert `const RzPVector*` {aka `const rz_pvector_t*`} to `const RzList*` {aka `const rz_list_t*`} in initialization
**Environment information**
* Operating System: Gentoo Linux (Kernel 5.15.80)
* Cutter version: Latest release (v2.3.1, commit 58f6c4d) 
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository

**Describe the bug**

Getting a cast error when compiling from source.

Commands used to build:
```bash
git clone https://github.com/rizinorg/cutter && cd cutter
git checkout v2.3.1
mkdir build
cmake -B build -DCUTTER_ENABLE_PYTHON=ON -DCUTTER_ENABLE_PYTHON_BINDINGS=ON -DCUTTER_ENABLE_KSYNTAXHIGHLIGHTING=ON -DCUTTER_ENABLE_GRAPHVIZ=ON -DCUTTER_EXTRA_PLUGIN_DIRS=ON -DCUTTER_USE_BUNDLED_RIZIN=OFF  
cmake --build build/
```

Error message after some seconds:
```c
...
[  6%] Building CXX object src/CMakeFiles/Cutter.dir/core/Cutter.cpp.o
/home/username/cutter/src/core/Cutter.cpp: In lambda function:
/home/username/cutter/src/core/Cutter.cpp:2375:44: warning: cast between incompatible function types from ‘int (*)(RzDebug*)’ {aka ‘int (*)(rz_debug_t*)’} to ‘RzConsBreak’ {aka ‘void (*)(void*)’} [-Wcast-function-type]
 2375 |                         rz_cons_break_push(reinterpret_cast<RzConsBreak>(rz_debug_stop), core->dbg);
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/username/cutter/src/core/Cutter.cpp: In member function ‘QList<ImportDescription> CutterCore::getAllImports()’:
/home/username/cutter/src/core/Cutter.cpp:3110:54: error: cannot convert ‘const RzPVector*’ {aka ‘const rz_pvector_t*’} to ‘const RzList*’ {aka ‘const rz_list_t*’} in initialization
 3110 |     const RzList *imports = rz_bin_object_get_imports(bf->o);
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                                      |
      |                                                      const RzPVector* {aka const rz_pvector_t*}
gmake[2]: *** [src/CMakeFiles/Cutter.dir/build.make:383: src/CMakeFiles/Cutter.dir/core/Cutter.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:101: src/CMakeFiles/Cutter.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**To Reproduce**

1. Clone and compile with the above commands.
2. See error after some seconds.

**Expected behavior**

Successful compilation.

**Additional context**

Rizin v0.6.1 compiled fine (built from rizinorg/rizin, same process but with the latest commit: https://github.com/rizinorg/rizin/commit/b82215965eb5de2dcd5cf06a5fc7d26d54f24b46 ), and `rz-ghidra` compiled fine as well using the `rz-pm` binary from the GitHub releases.

I have also been compiling `rz-retdec` with `rz-pm` for some time, and for now it doesn't seem to be any problem.

### PR DESCRIPTION
**Pull request by DMaroo**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

- `rz_debug_stop` returns an `int`, so we cannot cast it to `RxConsBreak`, which is a typedef of a function signature returning `void`
- `rz_debug_bp_add` siggnatue was recently modified, and thus Cutter couldn't build with the new signature
- `rz_bin_object_get_imports` was also modified recently to return a `RzPVector`, thus it also needed to be updated in Cutter

**Test plan (required)**

Green CI. Git submodule for Rizin has been updated to the latest dev commit: https://github.com/rizinorg/rizin/commit/a21f4bc7e7bc2a721e3afc4a2cbeeab0effeb564.

**Closing issues**

Helps in making the CI green for rizinorg/rz-ghidra#330.

Closes https://github.com/rizinorg/cutter/pull/3245
Closes https://github.com/rizinorg/cutter/issues/3239

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Requires also other `RzLIst` to `RzPVector` conversions:
```
/__w/cutter/cutter/src/core/Cutter.cpp:3560:49: error: cannot convert 'const RzPVector*' {aka 'const rz_pvector_t*'} to 'const RzList*' {aka 'const rz_list_t*'} in initialization
 3560 |     const RzList *cs = rz_bin_object_get_classes(bf->o);
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
      |                                                 |
      |                                                 const RzPVector* {aka const rz_pvector_t*}
[34/192] Building CXX object src/CMakeFiles/Cutter.dir/core/CutterJson.cpp.o
In file included from /__w/cutter/cutter/build/Rizin-prefix/include/librz/rz_parse.h:10,
                 from /__w/cutter/cutter/build/Rizin-prefix/include/librz/rz_asm.h:12,
                 from /__w/cutter/cutter/build/Rizin-prefix/include/librz/rz_egg.h:4,
                 from /__w/cutter/cutter/build/Rizin-prefix/include/librz/rz_core.h:14,
                 from /__w/cutter/cutter/src/core/CutterCommon.h:8,
                 from /__w/cutter/cutter/src/core/CutterJson.h:4,
                 from /__w/cutter/cutter/src/core/CutterJson.cpp:1:
/__w/cutter/cutter/build/Rizin-prefix/include/librz/rz_analysis.h: In function 'RzAnalysisVarKind rz_analysis_var_kind_from_string(const char*)':
/__w/cutter/cutter/build/Rizin-prefix/include/librz/rz_analysis.h:752:35: warning: comparison of integer expressions of different signedness: 'int' and 'long unsigned int' [-Wsign-compare]
  752 |                 for (int i = 0; i < RZ_ARRAY_SIZE(strings); ++i) { \
```
See https://github.com/rizinorg/rizin/issues/3775

**Comment by DMaroo** [comment]
Done. I just need to make a small change in Rizin, because Cutter seems to complain about a comparison of a signed with an unsigned int in a C macro in Rizin's code.

**Comment by XVilka** [comment]
> Done. I just need to make a small change in Rizin, because Cutter seems to complain about a comparison of a signed with an unsigned int in a C macro in Rizin's code.

Sure, please send a PR to Rizin too, lets merge it first before updating it here

**Comment by DMaroo** [comment]
Rizin PR: rizinorg/rizin#3875.

Merge strategy: Rizin -> Cutter -> rz-ghidra

**Comment by XVilka** [comment]
Seems one more error:
```
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(734): error C3480: 'RZ_ANALYSIS_VAR_KIND_INVALID': a lambda capture must be a variable from an enclosing function scope
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(734): error C3260: '=': skipping unexpected token(s) before lambda body
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(740): warning C4467: usage of ATL attributes is deprecated
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(740): error C2337: 'RZ_ANALYSIS_VAR_ORIGIN_NONE': attribute not found
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(740): error C2059: syntax error: '='
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(742): error C2059: syntax error: ';'
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(760): error C2070: 'const char *[]': illegal sizeof operand
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(761): error C2065: 'RzAnalysisVarOriginKind_strings': undeclared identifier
D:\a\cutter\cutter\build\include\librz\rz_analysis.h(761): error C2660: 'rz_str_cmp': function does not take 2 arguments
D:\a\cutter\cutter\build\include\librz\rz_util/rz_str.h(186): note: see declaration of 'rz_str_cmp'
```

**Comment by XVilka** [comment]
cc @imbillow

**Comment by DMaroo** [comment]
I am planning to remove the `rz_analysis.h` include altogether. Instead, we only need the `RzAnalysisOpType` enums, which I have split into another file. Waiting for rizinorg/rizin#3876 to get merged.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
