### PR TITLE
Convert to rizin api for `aoj`, `aht`, `dr*`

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

Partially addresses https://github.com/rizinorg/cutter/issues/2666

### CODE REVIEW

**Comment by XVilka** [comment]
Hmm, strange error:
```
CPack Error: Error when generating package: Cutter
FAILED: CMakeFiles/package.util 
cmd.exe /C "cd /D D:\a\cutter\cutter\build && "C:\Program Files\CMake\bin\cpack.exe" --config ./CPackConfig.cmake"
```
Could it be related to the recent changes in the Rizin's CMake files?
cc @thestr4ng3r @ret2libc

**Review by XVilka — APPROVED** [review]
The Windows error is unrelated to this PR and should be addressed separately.

**Comment by ret2libc** [comment]
> The Windows error is unrelated to this PR and should be addressed separately.

Why is it unrelated? `dev` seems green.

**Comment by XVilka** [comment]
@ret2libc it's because of the updating Rizin submodule, not the changes done by @imbillow

**Comment by ret2libc** [comment]
> @ret2libc it's because of the updating Rizin submodule, not the changes done by @imbillow

Shouldn't that be detected on `dev`?

**Comment by XVilka** [comment]
@ret2libc current Cutter `dev` uses older submodule commit: https://github.com/rizinorg/rizin/tree/be48ddcd9f0c2023d0e64750426c0476a13d8589

**Comment by ret2libc** [comment]
I'm blind, it seems :D Even though I looked for changes to the rizin submodule in this PR multiple times I could not see them. Ignore me.

**Review by thestr4ng3r — APPROVED** [review]

**Pull request merged**
