### PR TITLE
Cutter, fix build for Haiku which doesn't have O_ASYNC yet

### PR DESCRIPTION
**Pull request by Begasus**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Haiku doesn't have O_ASYNC yet, this fixes the build (with the latest radare2 release)

**Test plan (required)**

Cutter

**Closing issues**

### CODE REVIEW

**Comment by Begasus** [comment]
Patch isn't mine to take credit for see: https://github.com/haikuports/haikuports/pull/5434/files

**Review by ITAYC0HEN — APPROVED** [review]
Thank you for the contribution! :)
This looks fine to me. Compiled as usual on Arch and didn't experience a regression.

**Comment by Begasus** [comment]
This should be neutral to other ports/OS's, if there is a better fix we love to hear it :)

**Comment by karliss** [comment]
In general case O_ASYNC and O_NONBLOCK are not the same so maybe the define should be moved closer to usage and add a comment so that it's clearer that it's fine in this specific case.

Otherwise it's probably fine especially if test bellow succeeds.

Can you confirm that redirection is working and you get output in console widget? It can be opened using Windows/Console or "Ctrl+`". Some of the text in console widget gets printed directly, you can confirm if text you see uses output redirection by comparing against the output you see when running with "--no-output-redirect" flag.

**Comment by xarkes** [comment]
Hello @Begasus, could you confirm the redirection works as expected on Haiku?
Thanks :)

**Comment by Begasus** [comment]
Not an expert at these things, but here it goes:
Running Cutter without options from Terminal and enable Console output:
Cutter2
Running Cutter with the option mentioned in Terminal and enabled Console output gives an emtpy window, typing "?" gives some options though
Cutter3

**Comment by karliss** [comment]
Great that's the behavior I expected to see. It means that output redirection is working.

**Comment by ITAYC0HEN** [comment]
Cool! so the epxeriment works, then I think what's left is moving the `define` closer and adding a comment, right?

**Comment by Begasus** [comment]
> Cool! so the epxeriment works, then I think what's left is moving the `define` closer and adding a comment, right?

Somewhere just before: https://github.com/rizinorg/cutter/blob/master/src/widgets/ConsoleWidget.cpp#L437 ?

**Review by karliss — APPROVED** [review]

**Comment by Begasus** [comment]
Thanks! :+1:

**Pull request merged**
