### PR TITLE
Replace RZ_GITTIP with rz_str_gittip

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [ ] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

**Test plan (required)**

**Closing issues**

### CODE REVIEW

**Comment by wargio** [comment]
@kazarmy this was broken when you changed gittip, maybe is better to have a method in rizin to just fetch this?

**Comment by kazarmy** [comment]
sgtm

**Comment by XVilka** [comment]
@wargio it was merged, please update the PR.

**Comment by XVilka** [comment]
Hmm...
```
Dependency libzip skipped: feature use_sys_libzip disabled
Downloading libzip source from https://libzip.org/download/libzip-1.9.2.tar.gz

../../../../rizin/meson.build:584:2: ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
```
https://github.com/rizinorg/cutter/runs/7714081691?check_suite_focus=true#step:8:984

**Comment by XVilka** [comment]
@wargio see also https://github.com/rizinorg/cutter/pull/3008

**Comment by wargio** [comment]
maybe then close this.

**Pull request closed without merging**
