### PR TITLE
Add reverse debugging

### LINKED ISSUE #1022: Add step back/continue back
Add step back/continue back in emulation mode.

### PR DESCRIPTION
**Pull request by yossizap**
**Detailed description**

Basic reverse debug features, currently WIP since it's broken in all kinds of ways on r2's side for emulation(major issues) and all debug types(small bugs for each plugin).

reversedebug
reverdebugmenu

**Test plan (required)**

* Start and stop a tracing session multiple times.
* See that sessions are stopped when you exit debug.
* Start a trace session, step/continue forwards and then start stepping backwards
* Start a trace session, move forward to a certain point and see that continue backwards returns to the instruction you started tracing at or the nearest breakpoint
* Check that the register values are correctly restored after continue/step back

**Closing issues**

closes #1022

### CODE REVIEW

**Comment by xarkes** [comment]
Just a question: if it's broken in radare2, do we want to give the user the possibility to use a broken feature?

**Comment by yossizap** [comment]
No? it's WIP until it's fixed on r2's side.

>currently WIP since it's broken

**Comment by XVilka** [comment]
@yossizap @abcSup does this work now? Is there something left on the radare2 side?

**Comment by yossizap** [comment]
Waiting for the ESIL commands support from [#17507](https://github.com/radareorg/radare2/pull/17507) to move this PR out of WIP.

**Comment by XVilka** [comment]
By the way, https://github.com/radareorg/radare2/pull/17507 was merged.

**Comment by XVilka** [comment]
@abcSup @yossizap is there anything still required from the radare2 side?

**Comment by yossizap** [comment]
Nope and it's almost ready in Cutter, just need to finish testing and clean up

**Comment by ITAYC0HEN** [comment]
Hey @yossizap 👋 What's left in the cleaning up phase and how can we assist with the tests?

**Comment by yossizap** [comment]
Not much to help with, there's a crash in `r_debug_trace_ins_after` that I didn't have time to figure out yet. I'll push what I have after work if you are interested in doing additional testing.

**Comment by XVilka** [comment]
Please rebase on top of the master due to `R2Task` -> `RizinTask` rename.

**Comment by XVilka** [comment]
MacOS failure seems unrelated. cc @karliss

**Comment by wargio** [comment]
Please, resolve the conflicts.

**Review by ITAYC0HEN — APPROVED** [review]
I really like this feature and it worked quite good!
I did experience some issues but I couldn't reproduce them, sadly
hopefully we will be able to detect them

**Comment by officialcjunior** [comment]
I had tried the steps under your test plan on some very simple binaries and it worked like a charm. 👍🏾 

I tried it on Linux, by the way.

**Comment by XVilka** [comment]
Since I see you updated the Rizin submodule, what about using https://github.com/rizinorg/rizin/pull/467 then? Since it has fixes for Cutter 2.0

**Comment by xarkes** [comment]
Tested on Linux as well, and I didn't find any weird behavior!

**Review by xarkes — APPROVED** [review]
Test on Linux, couldn't see any weird/unexpected behavior, looks great!

**Comment by ITAYC0HEN** [comment]
@yossizap I think this can be merged as this got enough approvals. :)
Go on and merge it :tada: 

I'd love if @karliss  and @thestr4ng3r will still find the time to check this merged feature before the release as it is a fancy one. If you do find problems, please open an issue for them.

**Pull request merged**
